config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "store/index"
  get 'products/index'
  get "account/index"


  root :to => "store#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == ('admin' || 'proprietor' || 'developer') if request.env['warden'].user }, as: :admin_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'cashier' if request.env['warden'].user }, as: :cashier_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'retail_cashier' if request.env['warden'].user }, as: :retail_cashier_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'wholesale_cashier' if request.env['warden'].user }, as: :wholesale_cashier_root

  resources :products do
    get :autocomplete_product_name_and_description, on: :collection
    match "/scope_to_category" => "products#scope_to_category", as: :scope_to_category, via: [:get], on: :collection
    resources :stocks, module: :products do
      match "/delete" => "stocks#delete", as: :delete, via: [:get, :post]
      match "/add_to_expenses" => "stocks#add_to_expenses", as: :add_to_expenses, via: [:get, :post]
      match "/remove_from_expenses" => "stocks#remove_from_expenses", as: :remove_from_expenses, via: [:get, :post]
      resources :item_expenses, module: :stocks do
        match "/remove_from_expenses" => "item_expenses#remove_from_expenses", as: :remove_from_expenses, via: [:get, :post]
      end
    end
    resources :barcodes, module: :products
    match "/cash_sales" => "products#cash_sales", as: :cash_sales, via: [:get], on: :member
    match "/credit_sales" => "products#credit_sales", as: :credit_sales, via: [:get], on: :member
    match "/stock_histories" => "products#stock_histories", as: :stock_histories, via: [:get], on: :member
    match "/deleted" => "products#deleted", as: :deleted, via: [:get], on: :member
    match "/barcode" => "products#barcode", as: :barcode, via: [:get], on: :member
    match "/reports" => "products#reports", as: :reports, via: [:get], on: :member
    match "/scope_to_date_cash_sales" => "products#scope_to_date_cash_sales",  via: [:get], on: :member
    match "/scope_to_date_credit_sales" => "products#scope_to_date_credit_sales",  via: [:get], on: :member
    match "/scope_to_date_sales" => "products#scope_to_date_sales",  via: [:get], on: :member
    collection { post :import}
    match "/download" => "products#download", as: :download, via: [:get], on: :collection
    match "/export" => "products#export", as: :export, via: [:get], on: :collection
  end
  namespace :products do
    resources :imports, only: [:create]
  end
  resources :barcodes do
    collection { post :import}
  end

  resources :credit_collections do
    match "/scope_to_date" => "credit_collections#scope_to_date",  via: [:get], on: :collection
  end

  resources :carts
  resources :line_items do
    match "/return" => "line_items#return", as: :return, via: [:get, :post]
  end
  resources :orders do
    match "/guest" => "orders#guest",  via: [:post], on: :member
    match "/print" => "orders#print",  via: [:get], on: :member
    match "/print_invoice" => "orders#print_invoice",  via: [:get], on: :member
    match "/print_official_receipt" => "orders#print_official_receipt",  via: [:get], on: :member
    match "/scope_to_date" => "orders#scope_to_date",  via: [:get], on: :collection
    match "/monthly_summary_report" => "orders#monthly_summary_report",  via: [:get], on: :collection
    match "/retail_and_wholesale" => "orders#retail_and_wholesale", as: :retail_and_wholesale, via: [:get], on: :collection
    match "/retail" => "orders#retail", as: :retail, via: [:get], on: :collection
    match "/wholesale" => "orders#wholesale", as: :wholesale, via: [:get], on: :collection
    match "/return" => "orders#return", as: :return, via: [:get, :post]
  end

  resources :members, only: [:new, :create, :edit, :update]
  resources :lenders, only: [:new, :create, :edit, :update]
  resources :organizations, only: [:new, :create, :edit, :update]
  resources :customers do
    collection { post :import}
    get :autocomplete_customer_full_name, on: :collection

    match "/info" => "customers#info", as: :info, via: [:get], on: :member
    match "/purchases" => "customers#purchases", as: :purchases, via: [:get], on: :member
    match "/account_details" => "customers#account_details", as: :account_details, via: [:get], on: :member
    match "/payments" => "customers#payments", as: :payments, via: [:get], on: :member
    match "/advances" => "customers#advances", as: :advances, via: [:get], on: :member
    match "/advance_payments" => "customers#advance_payments", as: :advance_payments, via: [:get], on: :member

    resources :line_items, only: [:index], module: :customers do
      match "/scope_to_date" => "line_items#scope_to_date",  via: [:get], on: :collection, module: :customers
    end
    resources :advances, only: [:new, :create], module: :customers do
      match "/scope_to_date" => "advances#scope_to_date",  via: [:get], on: :collection, module: :customers
    end
    resources :advance_payments, only: [:new, :create], module: :customers do
      match "/scope_to_date" => "advance_payments#scope_to_date",  via: [:get], on: :collection, module: :customers
    end
    resources :payments, only: [:new, :create], module: :customers do
      match "/scope_to_date" => "payments#scope_to_date",  via: [:get], on: :collection, module: :customers
    end

    match "/export" => "customers#export", as: :export, via: [:get], on: :collection
  end
  
  resources :payables, only: [:index]
  resources :suppliers, :except => [:destroy] do
    get :autocomplete_supplier_owner, on: :collection
    resources :payments, only: [:new, :create], module: :suppliers
    match "/cash_stocks" => "suppliers#cash_stocks", as: :cash_stocks, via: [:get], on: :member
    match "/credit_stocks" => "suppliers#credit_stocks", as: :credit_stocks, via: [:get], on: :member
    match "/credit_payments" => "suppliers#credit_payments", as: :credit_payments, via: [:get], on: :member

  end
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :credits, only: [:index]
  resources :available_products, only: [:index]
  resources :low_stock_products, only: [:index]
  resources :out_of_stock_products, only: [:index]
  resources :expired_products, only: [:index]
  resources :one_month_expiry_products, only: [:index]
  resources :cash_advances, only: [:index]

  resources :wholesales do
    match "/botika" => "wholesales#botika", via: [:get], on: :collection
    match "/pharmacy" => "wholesales#pharmacy", via: [:get], on: :collection
  end
  resources :stocks, only: [:index, :show, :new, :create, :destroy] do
    collection { post :import}
    get :autocomplete_stock_name, on: :collection
    match "/scope_to_date" => "stocks#scope_to_date",  via: [:get], on: :collection
    match "/expired" => "stocks#expired", via: [:get], on: :collection
    match "/out_of_stock" => "stocks#out_of_stock", via: [:get], on: :collection
    match "/export" => "stocks#export", as: :export, via: [:get], on: :collection
  end

  namespace :wholesales do
    resources :line_items
    resources :orders
  end
  resources :businesses
  resources :users, only: [:show, :edit, :update] do 
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
  resources :employees, only: [:new, :create]
  resources :accounting, only: [:active_accounts, :inactive_accounts] do
    get :autocomplete_account_name, on: :collection
    match "/active_accounts" => "accounting#active_accounts", as: :active_accounts, via: [:get], on: :collection
    match "/inactive_accounts" => "accounting#inactive_accounts", as: :inactive_accounts, via: [:get], on: :collection
  end
  namespace :accounting do
    resources :balance_sheets, only:[:index, :scope_to_date] do
      match "/scope_to_date" => "balance_sheets#scope_to_date", via: [:get], on: :collection
    end
    resources :income_statements, only:[:index, :scope_to_date] do
      match "/scope_to_date" => "income_statements#scope_to_date", via: [:get], on: :collection
    end
    resources :dashboard, only: [:index]
    resources :reports, only:[:index]
    resources :accounts do
      get :autocomplete_accounting_account_name, on: :collection
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member
    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :fund_transfers, only: [:new, :create]
    resources :remittances, only: [:new, :create]
    resources :payables, only: [:new, :create]
    resources :disbursements, only: [:new, :create]
    resources :advances

    resources :entries do
      get :autocomplete_entry_description, on: :collection
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
  end

  namespace :owner do
    resources :dashboard, only: [:index]
  end
  resources :warranties, only: [:new, :create]
  resources :birs
  resources :retail_pricelists, only: [:index]

app/controllers/products/barcodes_controller.rb
module Products
  class BarcodesController < ApplicationController
    def new
      @product = Product.find(params[:product_id])
      @barcode = @product.barcodes.build
    end

    def create
      @product = Product.find(params[:product_id])
      @barcode = @product.barcodes.create(barcode_params)
    end

    def edit
      @product = Product.find(params[:product_id])
      @barcode = Barcode.find(params[:id])
    end

    def update
      @product = Product.find(params[:product_id])
      @barcode = @product.barcodes.find(params[:id])
      @barcode.update(barcode_params)
    end

    def destroy
      @product = Product.find(params[:product_id]) if params[:product_id].present?
      @barcode = Barcode.find(params[:id])
      @barcode.destroy
      redirect_to barcode_product_path(@product), alert: 'Barcode deleted successfully.'
    end
    
    private
    def barcode_params
      params.require(:barcode).permit(:code)
    end
  end
end

app/controllers/products/imports_controller.rb
module Products
	class ImportsController < ApplicationController

		def create
	      @import = ProductImport.new(import_params).parse_records!
	      redirect_to products_url, notice: 'Products Imported'
	  end

	  private
	  def import_params
	  	params.require(:product_import).permit(:spreadsheet_file, :employee_id)
	  end
	end
end

app/controllers/products/stocks/item_expenses_controller.rb
module Products
	module Stocks
		class ItemExpensesController < ApplicationController

			def new
				@stock = Stock.find(params[:stock_id])
				@product = @stock.product
				@item_expense = @stock.item_expenses.build
			end

			def create
				@stock = Stock.find(params[:stock_id])
				@product = @stock.product
				@item_expense = @stock.item_expenses.create(item_expense_params)
				@item_expense.create_expense_from_stock!
			end

			def show
				@item_expense = ItemExpense.find(params[:id])
				@stock = @item_expense.stock
				@product = @item_expense.product
			end

			def remove_from_expenses
				@item_expense = ItemExpense.find(params[:item_expense_id])
	      @stock = @item_expense.stock
				@product = Product.find(params[:product_id])
	      @item_expense.remove_stock_from_expense!
	      @item_expense.destroy
	      redirect_to stock_histories_product_path(@product), alert: "#{@item_expense.quantity} #{@product.unit} of #{@product.name_and_description} with total amount of P#{@item_expense.amount} has been removed from expenses."
	    end

			private
				def item_expense_params
					params.require(:item_expense).permit(:quantity, :expense_type, :employee_id, :product_id)
				end
		end
	end
end

app/controllers/products/stocks_controller.rb
module Products
  class StocksController < ApplicationController
    def new
      @product = Product.find(params[:product_id])
      @available = @product.stocks.where(deleted: false).order(date: :desc)
      @stocks = Kaminari.paginate_array(@available).page(params[:page]).per(30)
      @stock = @product.stocks.build
    end

    def create
      @product = Product.find(params[:product_id])
      @stock = @product.stocks.create(stock_params)
      @stock.employee = current_user
      if @stock.save
        ActiveRecord::Base.transaction do
          @stock.create_entry
          @stock.set_status!
          @stock.product.set_status!
        end
        redirect_to stock_histories_product_path(@product), notice: "New stock saved successfully."
      else
        render :new
      end
    end

    def edit
      @product = Product.find(params[:product_id])
      @stock = Stock.find(params[:id])
    end

    def update
      @product = Product.find(params[:product_id])
      @stock = @product.stocks.find(params[:id])
      if @stock.update(stock_params)
        ActiveRecord::Base.transaction do
          @stock.update_entry
          @stock.set_status!
          @stock.product.set_status!
        end
        redirect_to stock_histories_product_path(@product), notice: "Stock updated successfully."
      end
    end

    def show
      @product = Product.find(params[:product_id])
      @stock = @product.stocks.find(params[:id])
    end

    def delete
      @product = Product.find(params[:product_id])
      @stock = @product.stocks.find(params[:stock_id])
      if @stock.in_stock.zero?
        @stock.delete!
        redirect_to stock_histories_product_path(@product), alert: 'Stocks deleted successfully.'
      else
        redirect_to stock_histories_product_path(@product), alert: "Unable to delete stock, #{@stock.in_stock} #{@product.unit} still remains and not expired."
      end
    end

    def add_to_expenses
      @product = Product.find(params[:product_id])
      @stock = @product.stocks.find(params[:stock_id])
      if @stock.in_stock != 0 && @stock.expired?
        @stock.create_expense_from_expired_stock!
        redirect_to stock_histories_product_path(@product), alert: "#{@stock.in_stock} #{@product.unit} of #{@product.name_and_description} with total amount of P#{@stock.in_stock_amount} has been added to expenses."
      else
        redirect_to stock_histories_product_path(@product), alert: "Cannot add to expenses. Not out of stock or expired."
      end
    end

    def remove_from_expenses
      @product = Product.find(params[:product_id])
      @stock = @product.stocks.find(params[:stock_id])
      @stock.remove_expense_from_expired_stock!
      redirect_to stock_histories_product_path(@product), alert: "#{@stock.in_stock} #{@product.unit} of #{@product.name_and_description} with total amount of P#{@stock.in_stock_amount} has been removed from expenses."
    end

    def destroy
      @product = Product.find(params[:product_id]) if params[:product_id].present?
      @stock = Stock.find(params[:stock_id])
      if @stock.line_items.blank?
        @stock.destroy
        redirect_to stock_histories_product_path(@product), alert: 'Stock deleted successfully.'
      else
        @stock.delete!
        redirect_to stock_histories_product_path(@stock), alert: "Stock deleted successfully."
      end
    end
    
    private
    def stock_params
      params.require(:stock).permit(:lot_number, :payment_type, :supplier_id, :reference_number, :quantity, :date, :total_cost, :expiry_date, :unit_cost)
    end
  end
end

app/views/products/histories/_barcode.html.erb
<div class="tab-pane <%='active' if current_page? barcode_product_path %>">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Code</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @barcodes.each do |barcode| %>
        <tr>
          <td><%=barcode.code %></td>
          <td>
            <%= link_to "Edit", edit_product_barcode_path(product_id: @product.id, id: barcode.id), class: 'btn btn-success btn-xs', remote: true %>
            &nbsp &nbsp &nbsp
            <%= link_to "Delete", product_barcode_path(product_id: @product.id, id: barcode.id), method: :delete, data: {confirm: "Are you sure to delete this barcode?" }, class: 'btn btn-danger btn-xs' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <center><%= paginate @barcodes, :window => 1 %></center>
  </div>
</div>
<div id="barcode-modal" class="modal fade"></div>

app/views/products/histories/_cash_sales.html.erb
<div class="tab-pane <%='active' if current_page? cash_sales_product_path %>">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Customer </th>
        <th>QTY </th>
        <th>Lot Number </th>
        <th>Unit Cost </th>
        <th>Total Sales</th>
        <th>Cost of Goods Sold</th>
        <!-- <th> Income </th> -->

      </tr>
    </thead>
    <tbody>
      <% @results.to_a.sort_by(&:order_date).reverse.each do |line_item| %>
        <tr>
        <% if line_item.order.present? %>
          <td><%=line_item.order.date.strftime("%B %e, %Y") %></td>
          <td><%=line_item.order.try(:customer)%></td>
          <td><%=line_item.quantity %> <%=line_item.stock.product.unit %></td>
          <td><%=line_item.stock.lot_number %></td>
          <td><%=number_to_currency line_item.unit_price %></td>
          <td><%=number_to_currency line_item.total_price %></td>
          <td><%=number_to_currency line_item.cost_of_goods_sold %></td>
          <!-- <td><%=number_to_currency line_item.income %></td> -->
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <center><%= paginate @results, :window => 1 %></center>
  </div>
</div>

app/views/products/histories/_credit_sales.html.erb
<div class="tab-pane <%='active' if current_page? credit_sales_product_path %>">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Customer </th>
        <th>QTY </th>
        <th>Lot Number </th>
        <th>Unit Cost </th>
        <th>Total Sales</th>
        <th>Cost of Goods Sold</th>
        <!-- <th> Income </th> -->

      
      </tr>
    </thead>
    <tbody>
      <% @results.each do |line_item| %>
        <tr>
        <% if line_item.order.present? %>
          <td><%=line_item.order.date.strftime("%B %e, %Y") %></td>
          <td><%=line_item.order.try(:customer)%></td>
          <td><%=line_item.quantity %> <%=line_item.stock.product.unit %></td>
          <td><%=line_item.stock.lot_number %></td>
          <td><%=number_to_currency line_item.unit_price %></td>
          <td><%=number_to_currency line_item.total_price %></td>
          <td><%=number_to_currency line_item.cost_of_goods_sold %></td>
          <!-- <td><%=number_to_currency line_item.income %></td> -->

        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <center><%= paginate @results, :window => 1 %></center>
  </div>
</div>

app/views/products/histories/_damaged_and_lost.html.erb
<div class="tab-pane <%='active' if current_page? deleted_product_path %>">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Purchase Date</th>
        <th></th>
        <th>Qty </th>
        <th>Sold </th>
        <th>In Stock </th>
        <th>Unit</th>
        <th>Supplier</th>
        <th>Lot Number</th>
        <th>Exp. Date </th>
        <th>Unit Cost </th>
        <th>Total Purchase </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%@deleted.each do |stock| %>
        <tr>
          <td><%=link_to stock.date.strftime('%B %e, %Y'), product_stock_path(product_id: @product.id, id: stock.id), remote: true %></td>
          <td>
            <small class='label label-danger'><%=stock.alert %></small>
          </td>
          <td><%=stock.quantity %></td>
          <td><%=stock.sold %></td>
           <td><%=stock.in_stock %></td>
          <td><%=stock.product.unit %></td>
          <td><%=stock.supplier.business_name %></td>
          <td><%= stock.lot_number %></td>
          <td>
            <% if stock.expiry_date.present? %>
              <%= stock.expiry_date.strftime("%b %e, %Y") %>
            <% else %>
              N/A
            <% end %>
          </td>
          <td><%= number_to_currency stock.unit_cost %></td>
          <td><%=number_to_currency stock.total_cost %></td>
          <td class="pull-right">
            <%= link_to "Details", product_stock_path(product_id: @product.id, id: stock.id), class: 'btn btn-xs btn-info', remote: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <center><%= paginate @deleted, :window => 1 %></center>
  </div>
</div>

app/views/products/histories/_deleted.html.erb
<div class="tab-pane <%='active' if current_page? deleted_product_path %>">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Purchase Date</th>
        <th></th>
        <th>Qty </th>
        <th>Unit</th>
        <th>Supplier</th>
        <th>Lot Number</th>
        <th>Exp. Date </th>
        <th>Unit Cost </th>
        <th>Total Purchase </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%@deleted.each do |item_expense| %>
        <% if item_expense.class.name == "Stock" %>
          <tr>
            <td><%=link_to item_expense.date.strftime('%B %e, %Y'), product_stock_path(product_id: @product.id, id: item_expense.id), remote: true %></td>
            <td>
              <small class='label label-danger'>
                <% if item_expense.alert.present? %>
                  <%=item_expense.alert.titleize %>
                <% else %>
                  N/A
                <% end %>
              </small>
            </td>
            <td><%=item_expense.quantity %></td>
            <td><%=item_expense.product.unit %></td>
            <td><%=item_expense.supplier.business_name %></td>
            <td><%= item_expense.try(:lot_number) %></td>
            <td>
              <% if item_expense.expiry_date.present? %>
                <%= item_expense.expiry_date.strftime("%b %e, %Y") %>
              <% else %>
                N/A
              <% end %>
            </td>
            <td><%= number_to_currency item_expense.unit_cost %></td>
            <td><%= number_to_currency (item_expense.quantity * item_expense.unit_cost) %></td>
            <td class="pull-right">
              <% if item_expense.expired? %>
                <%= link_to "Details", product_stock_path(product_id: @product.id, id: item_expense.id), class: 'btn btn-xs btn-info', remote: true %>
              <% else %>
                <%= link_to "Details", product_stock_path(product_id: item_expense.product.id, id: item_expense.id), class: 'btn btn-xs btn-info', remote: true %>
              <% end %>
            </td>
          </tr>
        <% else %>
          <tr>
            <td><%=link_to item_expense.created_at.strftime('%B %e, %Y'), product_stock_path(product_id: @product.id, id: item_expense.stock.id), remote: true %></td>
            <td><small class='label label-danger'><%=item_expense.expense_type.titleize %></small></td>
            <td><%=item_expense.quantity %></td>
            <td><%=item_expense.product.unit %></td>
            <td><%=item_expense.stock.supplier.business_name %></td>
            <td><%= item_expense.stock.lot_number %></td>
            <td>
              <% if item_expense.stock.expiry_date.present? %>
                <%= item_expense.stock.expiry_date.strftime("%b %e, %Y") %>
              <% else %>
                N/A
              <% end %>
            </td>
            <td><%= number_to_currency item_expense.stock.unit_cost %></td>
            <td><%=number_to_currency (item_expense.quantity * item_expense.stock.unit_cost) %></td>
            <td class="pull-right">
              <% if item_expense.expired? %>
                <%= link_to "Details", product_stock_path(product_id: @product.id, id: item_expense.stock.id), class: 'btn btn-xs btn-info', remote: true %>
              <% else %>
                <%= link_to "Details", product_stock_item_expense_path(product_id: item_expense.product.id, stock_id: item_expense.stock.id, id: item_expense.id), class: 'btn btn-xs btn-info', remote: true %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <center><%= paginate @deleted, :window => 1 %></center>
  </div>
</div>
<div id="item-expense-show-modal" class="modal fade"></div>
<div id="stock-show-modal" class="modal fade"></div>

app/views/products/histories/_stock_histories.html.erb
<div class="tab-pane <%='active' if current_page? stock_histories_product_path %>">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Purchase Date</th>
        <th></th>
        <th>Qty </th>
        <th>Sold </th>
        <th>In Stock </th>
        <th>Unit</th>
        <th>Supplier</th>
        <th>Lot Number</th>
        <th>Exp. Date </th>
        <th>Unit Cost </th>
        <th>Total Purchase </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%@stocks.each do |stock| %>
        <tr>
          <td><%=link_to stock.date.strftime('%B %e, %Y'), product_stock_path(product_id: @product.id, id: stock.id), remote: true %></td>
          <td>
            <small class='label label-<%= "danger" if stock.alert == "Expired"%><%= "danger" if stock.alert == "Out of Stock"%><%="warning" if stock.alert == "Low Stock"%>'><%=stock.alert %></small>
          </td>
          <td><%=stock.quantity %></td>
          <td><%=stock.sold %></td>
           <td><%=stock.in_stock %></td>
          <td><%=stock.product.unit %></td>
          <td><%=stock.supplier.business_name %></td>
          <td><%= stock.lot_number %></td>
          <td>
            <% if stock.expiry_date.present? %>
              <%= stock.expiry_date.strftime("%b %e, %Y") %>
            <% else %>
              N/A
            <% end %>
          </td>
          <td><%= number_to_currency stock.unit_cost %></td>
          <td><%=number_to_currency stock.total_cost %></td>
          <td class="pull-right">
            <a tabindex="0" id="details" class="btn btn-xs btn-info" role="button" data-toggle="popover" data-placement="left" data-html="true" data-trigger="focus" title="Options" data-content='
              <%= link_to "Details", product_stock_path(product_id: @product.id, id: stock.id), class: "btn btn-xs btn-info btn-block", remote: true %>
              <% if current_user.proprietor? || current_user.developer? %>
                <%= link_to "Edit Stock", edit_product_stock_path(product_id: @product.id, id: stock.id), class: "btn btn-xs btn-warning btn-block" %> 
              <% end %>
              <% if stock.deleted? %>
                <%= link_to "Remove from Expenses", product_stock_remove_from_expenses_path(product_id: @product.id, stock_id: stock.id), data: {confirm: "You are trying to remove this stock from expense entries. It will be listed on stocks after confirmation. Do you wish to continue? "}, class: "btn btn-xs btn-success btn-block" %>
              <% else %>
                <%= link_to "Add to Expenses", new_product_stock_item_expense_path(product_id: @product.id, stock_id: stock.id), class: "btn btn-xs btn-danger btn-block", remote: true %>
                <% if stock.line_items.present? && (current_user.proprietor? || current_user.developer?) %>
                  <%= link_to "Delete Stock", product_stock_delete_path(product_id: @product.id, stock_id: stock.id), title: 'Delete Stock', data: {confirm: 'Are you sure you want to delete this stock? This action can not be undone.'}, class: "btn btn-xs btn-danger btn-block" %>
                <% else %>
                  <%= link_to "Delete Stock", product_stock_path(product_id: @product.id, stock_id: stock.id), method: :delete, data: {confirm: 'Are you sure you want to delete this stock? This action can not be undone.'}, class: "btn btn-xs btn-danger btn-block" %>
                <% end %>
              <% end %>'>
              Options
            </a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <center><%= paginate @stocks, :window => 1 %></center>
  </div>
</div>
<div id="stock-show-modal" class="modal fade"></div>
<div id="item-expense-modal" class="modal fade"></div>
<div id="product-modal" class="modal fade"></div>