config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "store/index"
  get 'products/index'
  get "account/index"


  root :to => "store#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == ('admin' || 'proprietor' || 'developer') if request.env['warden'].user }, as: :admin_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'cashier' if request.env['warden'].user }, as: :cashier_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'retail_cashier' if request.env['warden'].user }, as: :retail_cashier_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'wholesale_cashier' if request.env['warden'].user }, as: :wholesale_cashier_root

  resources :products do
    get :autocomplete_product_name_and_description, on: :collection
    match "/scope_to_category" => "products#scope_to_category", as: :scope_to_category, via: [:get], on: :collection
    resources :stocks, module: :products do
      match "/delete" => "stocks#delete", as: :delete, via: [:get, :post]
      match "/add_to_expenses" => "stocks#add_to_expenses", as: :add_to_expenses, via: [:get, :post]
      match "/remove_from_expenses" => "stocks#remove_from_expenses", as: :remove_from_expenses, via: [:get, :post]
      resources :item_expenses, module: :stocks do
        match "/remove_from_expenses" => "item_expenses#remove_from_expenses", as: :remove_from_expenses, via: [:get, :post]
      end
    end
    resources :barcodes, module: :products
    match "/cash_sales" => "products#cash_sales", as: :cash_sales, via: [:get], on: :member
    match "/credit_sales" => "products#credit_sales", as: :credit_sales, via: [:get], on: :member
    match "/stock_histories" => "products#stock_histories", as: :stock_histories, via: [:get], on: :member
    match "/deleted" => "products#deleted", as: :deleted, via: [:get], on: :member
    match "/barcode" => "products#barcode", as: :barcode, via: [:get], on: :member
    match "/reports" => "products#reports", as: :reports, via: [:get], on: :member
    match "/scope_to_date_cash_sales" => "products#scope_to_date_cash_sales",  via: [:get], on: :member
    match "/scope_to_date_credit_sales" => "products#scope_to_date_credit_sales",  via: [:get], on: :member
    match "/scope_to_date_sales" => "products#scope_to_date_sales",  via: [:get], on: :member
    collection { post :import}
    match "/download" => "products#download", as: :download, via: [:get], on: :collection
    match "/export" => "products#export", as: :export, via: [:get], on: :collection
  end
  namespace :products do
    resources :imports, only: [:create]
  end
  resources :barcodes do
    collection { post :import}
  end

  resources :credit_collections do
    match "/scope_to_date" => "credit_collections#scope_to_date",  via: [:get], on: :collection
  end

  resources :carts
  resources :line_items do
    match "/return" => "line_items#return", as: :return, via: [:get, :post]
  end
  resources :orders do
    match "/guest" => "orders#guest",  via: [:post], on: :member
    match "/print" => "orders#print",  via: [:get], on: :member
    match "/print_invoice" => "orders#print_invoice",  via: [:get], on: :member
    match "/print_official_receipt" => "orders#print_official_receipt",  via: [:get], on: :member
    match "/scope_to_date" => "orders#scope_to_date",  via: [:get], on: :collection
    match "/monthly_summary_report" => "orders#monthly_summary_report",  via: [:get], on: :collection
    match "/retail_and_wholesale" => "orders#retail_and_wholesale", as: :retail_and_wholesale, via: [:get], on: :collection
    match "/retail" => "orders#retail", as: :retail, via: [:get], on: :collection
    match "/wholesale" => "orders#wholesale", as: :wholesale, via: [:get], on: :collection
    match "/return" => "orders#return", as: :return, via: [:get, :post]
  end

  resources :members, only: [:new, :create, :edit, :update]
  resources :lenders, only: [:new, :create, :edit, :update]
  resources :organizations, only: [:new, :create, :edit, :update]
  resources :customers do
    collection { post :import}
    get :autocomplete_customer_full_name, on: :collection

    match "/info" => "customers#info", as: :info, via: [:get], on: :member
    match "/purchases" => "customers#purchases", as: :purchases, via: [:get], on: :member
    match "/account_details" => "customers#account_details", as: :account_details, via: [:get], on: :member
    match "/payments" => "customers#payments", as: :payments, via: [:get], on: :member
    match "/advances" => "customers#advances", as: :advances, via: [:get], on: :member
    match "/advance_payments" => "customers#advance_payments", as: :advance_payments, via: [:get], on: :member

    resources :line_items, only: [:index], module: :customers do
      match "/scope_to_date" => "line_items#scope_to_date",  via: [:get], on: :collection, module: :customers
    end
    resources :advances, only: [:new, :create], module: :customers do
      match "/scope_to_date" => "advances#scope_to_date",  via: [:get], on: :collection, module: :customers
    end
    resources :advance_payments, only: [:new, :create], module: :customers do
      match "/scope_to_date" => "advance_payments#scope_to_date",  via: [:get], on: :collection, module: :customers
    end
    resources :payments, only: [:new, :create], module: :customers do
      match "/scope_to_date" => "payments#scope_to_date",  via: [:get], on: :collection, module: :customers
    end

    match "/export" => "customers#export", as: :export, via: [:get], on: :collection
  end
  
  resources :payables, only: [:index]
  resources :suppliers, :except => [:destroy] do
    get :autocomplete_supplier_owner, on: :collection
    resources :payments, only: [:new, :create], module: :suppliers
    match "/cash_stocks" => "suppliers#cash_stocks", as: :cash_stocks, via: [:get], on: :member
    match "/credit_stocks" => "suppliers#credit_stocks", as: :credit_stocks, via: [:get], on: :member
    match "/credit_payments" => "suppliers#credit_payments", as: :credit_payments, via: [:get], on: :member

  end
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :credits, only: [:index]
  resources :available_products, only: [:index]
  resources :low_stock_products, only: [:index]
  resources :out_of_stock_products, only: [:index]
  resources :expired_products, only: [:index]
  resources :one_month_expiry_products, only: [:index]
  resources :cash_advances, only: [:index]

  resources :wholesales do
    match "/botika" => "wholesales#botika", via: [:get], on: :collection
    match "/pharmacy" => "wholesales#pharmacy", via: [:get], on: :collection
  end
  resources :stocks, only: [:index, :show, :new, :create, :destroy] do
    collection { post :import}
    get :autocomplete_stock_name, on: :collection
    match "/scope_to_date" => "stocks#scope_to_date",  via: [:get], on: :collection
    match "/expired" => "stocks#expired", via: [:get], on: :collection
    match "/out_of_stock" => "stocks#out_of_stock", via: [:get], on: :collection
    match "/export" => "stocks#export", as: :export, via: [:get], on: :collection
  end

  namespace :wholesales do
    resources :line_items
    resources :orders
  end
  resources :businesses
  resources :users, only: [:show, :edit, :update] do 
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
  resources :employees, only: [:new, :create]
  resources :accounting, only: [:active_accounts, :inactive_accounts] do
    get :autocomplete_account_name, on: :collection
    match "/active_accounts" => "accounting#active_accounts", as: :active_accounts, via: [:get], on: :collection
    match "/inactive_accounts" => "accounting#inactive_accounts", as: :inactive_accounts, via: [:get], on: :collection
  end
  namespace :accounting do
    resources :balance_sheets, only:[:index, :scope_to_date] do
      match "/scope_to_date" => "balance_sheets#scope_to_date", via: [:get], on: :collection
    end
    resources :income_statements, only:[:index, :scope_to_date] do
      match "/scope_to_date" => "income_statements#scope_to_date", via: [:get], on: :collection
    end
    resources :dashboard, only: [:index]
    resources :reports, only:[:index]
    resources :accounts do
      get :autocomplete_accounting_account_name, on: :collection
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member
    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :fund_transfers, only: [:new, :create]
    resources :remittances, only: [:new, :create]
    resources :payables, only: [:new, :create]
    resources :disbursements, only: [:new, :create]
    resources :advances

    resources :entries do
      get :autocomplete_entry_description, on: :collection
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
  end

  namespace :owner do
    resources :dashboard, only: [:index]
  end
  resources :warranties, only: [:new, :create]
  resources :birs
  resources :retail_pricelists, only: [:index]

app/controllers/wholesales/line_items_controller.rb
module Wholesales
  class LineItemsController < ApplicationController
    def create
      @cart = current_cart
      @line_item = @cart.line_items.create(line_item_params)
      respond_to do |format|
        if @line_item.save
          @line_item.wholesale!
          @cart.add_line_item(@line_item)
          format.html { redirect_to wholesales_url }
          format.js   { @current_item = @line_item }
        else
          format.html { redirect_to wholesales_url }
        end
      end
    end

    def destroy
      @cart = LineItem.find(params[:id])
      @cart.destroy
      redirect_to wholesales_url
    end

    private
    def line_item_params
      params.require(:line_item).permit(:user_id, :stock_id, :quantity, :unit_cost, :total_cost)
    end
  end
end

app/controllers/wholesales/orders_controller.rb
module Wholesales
  class OrdersController < ApplicationController
    def index
      @orders = Order.all.order(:created_at)
    end
    def new
      @cart = current_cart
        if @cart.line_items.empty?
          redirect_to wholesales_url, notice: "Your cart is empty."
        return
      end
      @order = Order.new
    end
    def create
      @order = Order.new(order_params)
      @order.add_line_items_from_cart(current_cart)
      @order.employee = current_user
      respond_to do |format|
        if @order.save
          @order.wholesale!
          @order.create_entry
          Cart.destroy(session[:cart_id])
          session[:cart_id] = nil
          format.html do
            if @order.credit?
              redirect_to print_order_url(@order), notice: 'Credit transaction saved successfully.'
            else
              redirect_to print_order_url(@order), notice: 'Thank you for your order.'
            end
          end
          format.json { render json: @order, status: :created,
          location: @order }
        else
          @cart = current_cart
          format.html { render action: "new" }
          format.json { render json: @order.errors,
          status: :unprocessable_entity }
        end
      end
      InvoiceNumber.new.generate_for(@order)
    end

    def show
      @order = Order.find(params[:id])
    end

    private
    def order_params
    params.require(:order).permit(:order_type, :customer_id, :cash_tendered, :change, :pay_type, :delivery_type, :date, :discounted, discount_attributes:[:amount])
  end
  end
end

app/controllers/wholesales_controller.rb
class WholesalesController < ApplicationController
  def botika
    if params[:name_and_description].present?
      @products = Product.search_by_name(params[:name_and_description]).pluck(:id)
      if @products.present?
        @stocks = Stock.order(date: :asc).joins(:product).where(products: { id: @products })
      else
        redirect_to botika_wholesales_path, notice: 'Product is either out of stock or expired.'
      end
    else
      @stocks = Stock.available
    end
    @cart = current_cart
    @line_item = LineItem.new
    @order = Order.new
    @order.build_discount
  end

  def pharmacy
    if params[:name_and_description].present?
      @products = Product.search_by_name(params[:name_and_description]).pluck(:id)
      if @products.present?
        @stocks = Stock.order(date: :asc).joins(:product).where(products: { id: @products })
      else
        redirect_to pharmacy_wholesales_path, notice: 'Product is either out of stock or expired.'
      end
    else
      @stocks = Stock.available
    end
    @cart = current_cart
    @line_item = LineItem.new
    @order = Order.new
    @order.build_discount
  end
end

app/views/wholesales/botika.html.erb
<div class="row">
  <div class="col-md-7">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          <div class="row">
            <div class="col-md-4">
              <%= link_to "Retail", store_index_path, class: 'btn btn-lg btn-default btn-block' %>
            </div>
            <div class="col-md-4">
              <%= link_to "Pharmacy", pharmacy_wholesales_path, class: 'btn btn-lg btn-default btn-block' %>
            </div>
            <div class="col-md-4">
              <%= link_to "Botika", botika_wholesales_path, class: 'btn btn-lg btn-info btn-block' %>
            </div>
          </div>
          <br>
          <div class="col-md-12">
            <% if params[:name_and_description].present? %>
              <%=form_tag botika_wholesales_path, method: :get do %>
                <div class="input-group stylish-input-group" id="product-prefetch">
                  <%= autocomplete_field_tag "name_and_description", params[:name_and_description], autocomplete_product_name_and_description_products_path, class: 'form-control input-lg', placeholder: 'Search Inventory...' %>
                  <span class="input-group-btn">
                    <%= button_tag(type: 'submit', class: "btn btn-flat btn-lg") do %>
                      <i class="fa fa-search"></i>
                    <% end %>
                  </span>
                </div>
              <% end %>
            <% else %>
              <%=form_tag botika_wholesales_path, method: :get do %>
                <div class="input-group stylish-input-group" id="product-prefetch">
                  <%= autocomplete_field_tag "name_and_description", params[:name_and_description], autocomplete_product_name_and_description_products_path, autofocus: true, class: 'form-control input-lg', placeholder: 'Search Inventory...' %>
                  <span class="input-group-btn">
                    <%= button_tag(type: 'submit', class: "btn btn-flat btn-lg") do %>
                      <i class="fa fa-search"></i>
                    <% end %>
                  </span>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card-body">
        <% if params[:name_and_description].present? && @stocks.count > 0 %>
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Product</th>
                <th class="text-right" width="110px">Price </th>
                <th class="text-center">Quantity </th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @stocks.available.each do |stock| %>
                <% unless stock.out_of_stock? || stock.expired? %>
                  <tr>
                    <%=simple_form_for @line_item, url: :line_items do |f| %>
                      <%= f.input :pricing_type, input_html: { value: "botika" } , as: :hidden %>
                      <td>
                        <h5><%=stock.product.name_and_description %></h5>
                        <p class="text-muted">
                          Remaining: <%=stock.in_stock%> <%=stock.product.unit%> | Exp. Date: <%=stock.expiry_date || "n/a"%>
                        </p>
                      </td>

                      <td width="130px">
                        <div class="pull-right">
                          <span>&nbsp</span><br>
                          <%=f.input :unit_price, input_html: { value: stock.product.botika_price}, label: false %>
                        </div>
                      </td>
                      <td width="110px"">
                        <span>&nbsp</span><br>
                        <%=f.input :quantity,  input_html: {value: 1, max: stock.in_stock}, autofocus: true, label: false %>
                        <%=f.input :stock_id, input_html: {value: stock.id }, as: :hidden %>
                      </td>
                      <td width="60px">
                        <span>&nbsp</span><br>
                        <div class="pull-right">
                          <%=f.submit "Add", data: {disable_with: "Adding Product..."}, class: "btn btn-primary btn-sm active" %>
                        </div>
                      </td>
                    <% end %>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        <% elsif @stocks.count.zero? && params[:name_and_description].present? %>
          <p class="alert alert-info"> Product not found or out of stock.<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> </p>
        <% end %>
      </div>
    </div>
    <div class="card ">
      <div class="card-header">
        <div class="card-title">
          <% if @cart.line_items.blank? %>
            <center><%=image_tag('empty_cart.png', height: 150, width: 150) %></center>
          <% else %>
            <h4> <i class="fa fa-cart-plus fa-2x"></i> <span class='badge badge-notify'><%=@cart.line_items.count %></span> <span>Items in Cart</span>
              <span class="pull-right">
                <%= link_to 'Empty Cart', @cart, method: :delete, data: {confirm: 'Are you sure you want to empty cart?'}, class: "btn btn-danger btn-xs" %>
              </span>
            </h4>
          <% end %>
        </div>
      </div>
      <div class="card-body">
        <%=render @cart.line_items.sort_by{|l| l.stock_name } %>
      </div>
    </div>
  </div>
  <% if @cart.line_items.present? %>
    <div class="col-md-5" id="cart">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-12">
              <div class="pull-left">
                <h2> <b>Sub Total</b> </h2>
              </div>
              <div class="pull-right">
                <h2> <b><%=number_to_currency @cart.total_amount %></b></h2>
              </div>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-12">
              <%=simple_form_for @order, url: :orders do |f| %>
                <%= f.input :order_type, input_html: {value: 'wholesale'}, as: :hidden %>
                <span>
                  <label>Customer</label>
                  <span class="pull-right">
                    <ul class="nav navbar-nav pull-right">
                    <li class="dropdown">
                      <button href="#" class="dropdown-toggle btn btn-success btn-xs" data-toggle="dropdown" aria-expanded="false">New Customer <b class="caret"></b></button>
                      <ul class="dropdown-menu dropdown-menu-right">
                        <li><%=link_to "Regular", new_member_path, remote: true %></li>
                        <li> <%=link_to 'Organization', new_organization_path, remote: true %></li>
                      </ul>
                    </li>
                  </ul>
                  </span>
                </span>
                <%=f.input :customer_id, label: false, collection: Customer.order(:id).all.map{|a| [a.full_name, a.id] }, default: Customer.find_by(first_name: "Guest"), input_html: {id: 'order_user_id'} %>
                <input type="hidden" name="total" id="total" value="<%= @cart.total_amount %>" oninput="calculateChange()">
                <div class="row">
                  <div class="col-md-5">
                    <%=f.input :pay_type, collection: Order.pay_types.keys.to_a.map{|a| [a.titleize, a]}, default: Order.pay_types.first%>
                  </div>
                  <div class="col-md-7">
                    <%=f.input :date, as: :string, input_html: {class: 'datepicker', value: Time.zone.now.strftime("%Y-%m-%d %I:%M %p")} %>
                  </div>
                </div>
                <%=f.input :discounted, as: :boolean, input_html: { id: 'order_discount'} %>
                <div id="discount_details" style="display:none;">
                  <%=f.simple_fields_for :discount do |ff| %>
                    <div class="form-group has-warning">
                     <%= ff.input :amount, input_html: {oninput: 'calculateChange()', class: 'input-lg text-warning', value: 0}, label: "Discount Amount" %>
                    </div>
                  <% end %>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <%=f.input :cash_tendered, input_html: {oninput: 'calculateChange()', class: 'input-lg'}, label: "Amount Tendered" %>
                  </div>
                  <div class="col-md-6">
                    <%=f.input :change, input_html: { class: 'input-lg'}, readonly: true %>
                  </div>
                </div>
                <%=f.submit "Checkout", class: 'btn btn-success btn-block btn-lg' %>
                <br>
              <% end %>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div id="member-modal" class="modal fade"></div>
<div id="organization-modal" class="modal fade"></div>
<script>
  $('#search').bind('railsAutocomplete.select', function(event, data){
  $('#search-form').submit()
  });
</script>
<script>
  $(document).ready(function() {
    $("#order_user_id").select2({
      theme: "bootstrap",
      width: "100%"
    });
  });
</script>
<script>
  var checkbox = document.getElementById('order_discount');
  var details_div = document.getElementById('discount_details');
  checkbox.onchange = function() {
     if(this.checked) {
       details_div.style['display'] = 'block';
     } else {
       details_div.style['display'] = 'none';
     }
  };
</script>